[package]
name = "float-x"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
rand = { version = "0.8.5", features = ["small_rng"] }

[dev-dependencies]
plotters = "0.3.5"
